/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...404]': RouteRecordInfo<
      '/[...404]',
      '/:404(.*)',
      { 404: ParamValue<true> },
      { 404: ParamValue<false> },
      | never
    >,
    '/demos': RouteRecordInfo<
      '/demos',
      '/demos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/nav': RouteRecordInfo<
      '/nav',
      '/nav',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/photos': RouteRecordInfo<
      '/photos',
      '/photos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ai-coding-workflow-matt-pocock': RouteRecordInfo<
      '/posts/ai-coding-workflow-matt-pocock',
      '/posts/ai-coding-workflow-matt-pocock',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/ai-native-sdlc-playbook': RouteRecordInfo<
      '/posts/ai-native-sdlc-playbook',
      '/posts/ai-native-sdlc-playbook',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/anthropic-multi-agent-research-system': RouteRecordInfo<
      '/posts/anthropic-multi-agent-research-system',
      '/posts/anthropic-multi-agent-research-system',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/arxiv-translation-tools': RouteRecordInfo<
      '/posts/arxiv-translation-tools',
      '/posts/arxiv-translation-tools',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/building-skills-for-claude': RouteRecordInfo<
      '/posts/building-skills-for-claude',
      '/posts/building-skills-for-claude',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/claude-code-dynamic-workflows': RouteRecordInfo<
      '/posts/claude-code-dynamic-workflows',
      '/posts/claude-code-dynamic-workflows',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/claude-model-and-effort-level': RouteRecordInfo<
      '/posts/claude-model-and-effort-level',
      '/posts/claude-model-and-effort-level',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/codex-agent-workbench': RouteRecordInfo<
      '/posts/codex-agent-workbench',
      '/posts/codex-agent-workbench',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/codex-auth-sync': RouteRecordInfo<
      '/posts/codex-auth-sync',
      '/posts/codex-auth-sync',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/codex-memory-implementation': RouteRecordInfo<
      '/posts/codex-memory-implementation',
      '/posts/codex-memory-implementation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/codex-remote': RouteRecordInfo<
      '/posts/codex-remote',
      '/posts/codex-remote',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/docker-for-ai': RouteRecordInfo<
      '/posts/docker-for-ai',
      '/posts/docker-for-ai',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/flash-attn-install-cross-device-link': RouteRecordInfo<
      '/posts/flash-attn-install-cross-device-link',
      '/posts/flash-attn-install-cross-device-link',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/git-commit-message': RouteRecordInfo<
      '/posts/git-commit-message',
      '/posts/git-commit-message',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/gtc-git-clone-cd': RouteRecordInfo<
      '/posts/gtc-git-clone-cd',
      '/posts/gtc-git-clone-cd',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/how-to-review': RouteRecordInfo<
      '/posts/how-to-review',
      '/posts/how-to-review',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/huggingface': RouteRecordInfo<
      '/posts/huggingface',
      '/posts/huggingface',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/linux-order': RouteRecordInfo<
      '/posts/linux-order',
      '/posts/linux-order',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/linux-ubuntu': RouteRecordInfo<
      '/posts/linux-ubuntu',
      '/posts/linux-ubuntu',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/llm-a-survey': RouteRecordInfo<
      '/posts/llm-a-survey',
      '/posts/llm-a-survey',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/maximizing-the-value-of-your-claude-code-sessions': RouteRecordInfo<
      '/posts/maximizing-the-value-of-your-claude-code-sessions',
      '/posts/maximizing-the-value-of-your-claude-code-sessions',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/oh-my-zsh': RouteRecordInfo<
      '/posts/oh-my-zsh',
      '/posts/oh-my-zsh',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/openclaw-feishu-tutorial': RouteRecordInfo<
      '/posts/openclaw-feishu-tutorial',
      '/posts/openclaw-feishu-tutorial',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/peanut-shell-intranet': RouteRecordInfo<
      '/posts/peanut-shell-intranet',
      '/posts/peanut-shell-intranet',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/research-tips-sharing': RouteRecordInfo<
      '/posts/research-tips-sharing',
      '/posts/research-tips-sharing',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/sci': RouteRecordInfo<
      '/posts/sci',
      '/posts/sci',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/slurm-gvitop-nvitop': RouteRecordInfo<
      '/posts/slurm-gvitop-nvitop',
      '/posts/slurm-gvitop-nvitop',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/train-gpt': RouteRecordInfo<
      '/posts/train-gpt',
      '/posts/train-gpt',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/wsl2mac': RouteRecordInfo<
      '/posts/wsl2mac',
      '/posts/wsl2mac',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects': RouteRecordInfo<
      '/projects',
      '/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/use': RouteRecordInfo<
      '/use',
      '/use',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'pages/index.md': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/[...404].md': {
      routes:
        | '/[...404]'
      views:
        | never
      pathParamNames:
        | '404'
    }
    'pages/demos.md': {
      routes:
        | '/demos'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/nav.md': {
      routes:
        | '/nav'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/photos.md': {
      routes:
        | '/photos'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/index.md': {
      routes:
        | '/posts/'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/ai-coding-workflow-matt-pocock.md': {
      routes:
        | '/posts/ai-coding-workflow-matt-pocock'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/ai-native-sdlc-playbook.md': {
      routes:
        | '/posts/ai-native-sdlc-playbook'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/anthropic-multi-agent-research-system.md': {
      routes:
        | '/posts/anthropic-multi-agent-research-system'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/arxiv-translation-tools.md': {
      routes:
        | '/posts/arxiv-translation-tools'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/building-skills-for-claude.md': {
      routes:
        | '/posts/building-skills-for-claude'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/claude-code-dynamic-workflows.md': {
      routes:
        | '/posts/claude-code-dynamic-workflows'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/claude-model-and-effort-level.md': {
      routes:
        | '/posts/claude-model-and-effort-level'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/codex-agent-workbench.md': {
      routes:
        | '/posts/codex-agent-workbench'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/codex-auth-sync.md': {
      routes:
        | '/posts/codex-auth-sync'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/codex-memory-implementation.md': {
      routes:
        | '/posts/codex-memory-implementation'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/codex-remote.md': {
      routes:
        | '/posts/codex-remote'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/docker-for-ai.md': {
      routes:
        | '/posts/docker-for-ai'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/flash-attn-install-cross-device-link.md': {
      routes:
        | '/posts/flash-attn-install-cross-device-link'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/git-commit-message.md': {
      routes:
        | '/posts/git-commit-message'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/gtc-git-clone-cd.md': {
      routes:
        | '/posts/gtc-git-clone-cd'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/how-to-review.md': {
      routes:
        | '/posts/how-to-review'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/huggingface.md': {
      routes:
        | '/posts/huggingface'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/linux-order.md': {
      routes:
        | '/posts/linux-order'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/linux-ubuntu.md': {
      routes:
        | '/posts/linux-ubuntu'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/llm-a-survey.md': {
      routes:
        | '/posts/llm-a-survey'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/maximizing-the-value-of-your-claude-code-sessions.md': {
      routes:
        | '/posts/maximizing-the-value-of-your-claude-code-sessions'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/oh-my-zsh.md': {
      routes:
        | '/posts/oh-my-zsh'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/openclaw-feishu-tutorial.md': {
      routes:
        | '/posts/openclaw-feishu-tutorial'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/peanut-shell-intranet.md': {
      routes:
        | '/posts/peanut-shell-intranet'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/research-tips-sharing.md': {
      routes:
        | '/posts/research-tips-sharing'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/sci.md': {
      routes:
        | '/posts/sci'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/slurm-gvitop-nvitop.md': {
      routes:
        | '/posts/slurm-gvitop-nvitop'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/train-gpt.md': {
      routes:
        | '/posts/train-gpt'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/posts/wsl2mac.md': {
      routes:
        | '/posts/wsl2mac'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/projects.md': {
      routes:
        | '/projects'
      views:
        | never
      pathParamNames:
        | never
    }
    'pages/use.md': {
      routes:
        | '/use'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
